spring:
  application:
    name: workbench
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  session:
    jdbc:
      initialize-schema: always
  jpa:
    generate-ddl: true
  data:
    rest:
      base-path: /api
      return-body-on-create: true
      return-body-on-update: true
      enable-enum-translation: true
logging:
  level:
    root: info
    de.kaleidox: debug
    org.comroid: debug
    com.ampznetwork: debug
