spring:
  application:
    name: workbench
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  session:
    jdbc:
      initialize-schema: always
  jpa:
    generate-ddl: true
  data:
    rest:
      base-path: /api
