name: background-services

volumes:
  database:

services:
  database:
    image: mariadb:lts
    restart: unless-stopped
    network_mode: host
    environment:
      MARIADB_USER: dev
      MARIADB_PASSWORD: dev
      MARIADB_DATABASE: dev
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ./run/database/dump.sql:/docker-entrypoint-initdb.d/dump.sql:r

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    network_mode: host
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      start_period: 5s
      interval: 30s
      timeout: 30s
      retries: 3
